In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
# 設定 data_path
dir_data = './data/'
f_app_train = os.path.join(dir_data, 'application_train.csv')
f_app_test = os.path.join(dir_data, 'application_test.csv')

app_train = pd.read_csv(f_app_train)
app_test = pd.read_csv(f_app_test)
print(app_train)
print(app_test)

        SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0           100002       1         Cash loans           M            N
1           100003       0         Cash loans           F            N
2           100004       0    Revolving loans           M            Y
3           100006       0         Cash loans           F            N
4           100007       0         Cash loans           M            N
5           100008       0         Cash loans           M            N
6           100009       0         Cash loans           F            Y
7           100010       0         Cash loans           M            Y
8           100011       0         Cash loans           F            N
9           100012       0    Revolving loans           M            N
10          100014       0         Cash loans           F            N
11          100015       0         Cash loans           F            N
12          100016       0         Cash loans           F            N
13          100017       0         Cash loans           M            Y
14          100018       0         Cash loans           F            N
15          100019       0         Cash loans           M            Y
16          100020       0         Cash loans           M            N
17          100021       0    Revolving loans           F            N
18          100022       0    Revolving loans           F            N
19          100023       0         Cash loans           F            N
20          100024       0    Revolving loans           M            Y
21          100025       0         Cash loans           F            Y
22          100026       0         Cash loans           F            N
23          100027       0         Cash loans           F            N
24          100029       0         Cash loans           M            Y
25          100030       0         Cash loans           F            N
26          100031       1         Cash loans           F            N
27          100032       0         Cash loans           M            N
28          100033       0         Cash loans           M            Y
29          100034       0    Revolving loans           M            N
...            ...     ...                ...         ...          ...
307481      456225       1         Cash loans           M            N
307482      456226       0         Cash loans           F            Y
307483      456227       0         Cash loans           F            N
307484      456228       0         Cash loans           F            Y
307485      456229       0    Revolving loans           F            N
307486      456230       0         Cash loans           F            Y
307487      456231       0         Cash loans           M            N
307488      456232       0         Cash loans           F            N
307489      456233       1         Cash loans           F            N
307490      456234       0         Cash loans           M            N
307491      456235       0         Cash loans           M            Y
307492      456236       0         Cash loans           M            Y
307493      456237       0         Cash loans           F            N
307494      456238       0         Cash loans           M            Y
307495      456239       0         Cash loans           M            Y
307496      456240       0    Revolving loans           F            N
307497      456241       0         Cash loans           F            Y
307498      456242       0         Cash loans           M            Y
307499      456243       0         Cash loans           F            N
307500      456244       0         Cash loans           F            N
307501      456245       0         Cash loans           F            N
307502      456246       0         Cash loans           F            N
307503      456247       0         Cash loans           F            N
307504      456248       0         Cash loans           F            N
307505      456249       0         Cash loans           F            N
307506      456251       0         Cash loans           M            N
307507      456252       0         Cash loans           F            N
307508      456253       0         Cash loans           F            N
307509      456254       1         Cash loans           F            N
307510      456255       0         Cash loans           F            N

       FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  \
0                    Y             0        202500.000    406597.5
1                    N             0        270000.000   1293502.5
2                    Y             0         67500.000    135000.0
3                    Y             0        135000.000    312682.5
4                    Y             0        121500.000    513000.0
5                    Y             0         99000.000    490495.5
6                    Y             1        171000.000   1560726.0
7                    Y             0        360000.000   1530000.0
8                    Y             0        112500.000   1019610.0
9                    Y             0        135000.000    405000.0
10                   Y             1        112500.000    652500.0
11                   Y             0         38419.155    148365.0
12                   Y             0         67500.000     80865.0
13                   N             1        225000.000    918468.0
14                   Y             0        189000.000    773680.5
15                   Y             0        157500.000    299772.0
16                   N             0        108000.000    509602.5
17                   Y             1         81000.000    270000.0
18                   Y             0        112500.000    157500.0
19                   Y             1         90000.000    544491.0
20                   Y             0        135000.000    427500.0
21                   Y             1        202500.000   1132573.5
22                   N             1        450000.000    497520.0
23                   Y             0         83250.000    239850.0
24                   N             2        135000.000    247500.0
25                   Y             0         90000.000    225000.0
26                   Y             0        112500.000    979992.0
27                   Y             1        112500.000    327024.0
28                   Y             0        270000.000    790830.0
29                   Y             0         90000.000    180000.0
...                ...           ...               ...         ...
307481               Y             0        225000.000    297000.0
307482               Y             0        225000.000    500566.5
307483               Y             0         99000.000    247275.0
307484               N             0        540000.000    545040.0
307485               Y             1        270000.000    180000.0
307486               Y             1        292500.000    355536.0
307487               Y             0        117000.000   1071909.0
307488               N             0        157500.000    135000.0
307489               Y             0        225000.000    521280.0
307490               Y             0         81000.000    135000.0
307491               Y             2         90000.000   1078200.0
307492               Y             0        585000.000   1575000.0
307493               Y             0        135000.000    946764.0
307494               N             1        270000.000    479700.0
307495               N             0        180000.000    808650.0
307496               N             0        360000.000    337500.0
307497               Y             0        180000.000    270126.0
307498               Y             0        198000.000   1312110.0
307499               Y             0         81000.000    225000.0
307500               Y             0        261000.000   1303812.0
307501               Y             3         81000.000    269550.0
307502               Y             1         94500.000    225000.0
307503               Y             0        112500.000    345510.0
307504               Y             0        153000.000    331920.0
307505               Y             0        112500.000    225000.0
307506               N             0        157500.000    254700.0
307507               Y             0         72000.000    269550.0
307508               Y             0        153000.000    677664.0
307509               Y             0        171000.000    370107.0
307510               N             0        157500.000    675000.0

        AMT_ANNUITY             ...              FLAG_DOCUMENT_18  \
0           24700.5             ...                             0
1           35698.5             ...                             0
2            6750.0             ...                             0
3           29686.5             ...                             0
4           21865.5             ...                             0
5           27517.5             ...                             0
6           41301.0             ...                             0
7           42075.0             ...                             0
8           33826.5             ...                             0
9           20250.0             ...                             0
10          21177.0             ...                             0
11          10678.5             ...                             0
12           5881.5             ...                             0
13          28966.5             ...                             0
14          32778.0             ...                             0
15          20160.0             ...                             0
16          26149.5             ...                             0
17          13500.0             ...                             0
18           7875.0             ...                             0
19          17563.5             ...                             0
20          21375.0             ...                             0
21          37561.5             ...                             0
22          32521.5             ...                             0
23          23850.0             ...                             0
24          12703.5             ...                             0
25          11074.5             ...                             0
26          27076.5             ...                             0
27          23827.5             ...                             0
28          57676.5             ...                             0
29           9000.0             ...                             0
...             ...             ...                           ...
307481      19975.5             ...                             0
307482      34969.5             ...                             0
307483      16479.0             ...                             0
307484      35617.5             ...                             0
307485       9000.0             ...                             0
307486      18283.5             ...                             0
307487      31473.0             ...                             0
307488      13351.5             ...                             0
307489      23089.5             ...                             0
307490       9148.5             ...                             0
307491      31522.5             ...                             0
307492      43443.0             ...                             0
307493      37678.5             ...                             0
307494      46858.5             ...                             0
307495      23773.5             ...                             0
307496      16875.0             ...                             0
307497      12028.5             ...                             0
307498      52168.5             ...                             0
307499      12694.5             ...                             0
307500      35982.0             ...                             0
307501      11871.0             ...                             0
307502      10620.0             ...                             0
307503      17770.5             ...                             0
307504      16096.5             ...                             0
307505      22050.0             ...                             0
307506      27558.0             ...                             0
307507      12001.5             ...                             0
307508      29979.0             ...                             0
307509      20205.0             ...                             0
307510      49117.5             ...                             0

       FLAG_DOCUMENT_19 FLAG_DOCUMENT_20 FLAG_DOCUMENT_21  \
0                     0                0                0
1                     0                0                0
2                     0                0                0
3                     0                0                0
4                     0                0                0
5                     0                0                0
6                     0                0                0
7                     0                0                0
8                     0                0                0
9                     0                0                0
10                    0                0                0
11                    0                0                0
12                    0                0                0
13                    0                0                0
14                    0                0                0
15                    0                0                0
16                    0                0                0
17                    0                0                0
18                    0                0                0
19                    0                0                0
20                    0                0                0
21                    0                0                0
22                    0                0                0
23                    0                0                0
24                    0                0                0
25                    0                0                0
26                    0                0                0
27                    0                0                0
28                    0                0                0
29                    0                0                0
...                 ...              ...              ...
307481                0                0                0
307482                0                0                0
307483                0                0                0
307484                0                0                0
307485                0                0                0
307486                0                0                0
307487                0                0                0
307488                0                0                0
307489                0                0                0
307490                0                0                0
307491                0                0                0
307492                0                0                0
307493                0                0                0
307494                0                0                0
307495                0                0                0
307496                0                0                0
307497                0                0                0
307498                0                0                0
307499                0                0                0
307500                0                0                0
307501                0                0                0
307502                0                0                0
307503                0                0                0
307504                0                0                0
307505                0                0                0
307506                0                0                0
307507                0                0                0
307508                0                0                0
307509                0                0                0
307510                0                0                0

       AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
0                             0.0                       0.0
1                             0.0                       0.0
2                             0.0                       0.0
3                             NaN                       NaN
4                             0.0                       0.0
5                             0.0                       0.0
6                             0.0                       0.0
7                             0.0                       0.0
8                             0.0                       0.0
9                             NaN                       NaN
10                            0.0                       0.0
11                            0.0                       0.0
12                            0.0                       0.0
13                            0.0                       0.0
14                            NaN                       NaN
15                            0.0                       0.0
16                            0.0                       0.0
17                            NaN                       NaN
18                            0.0                       0.0
19                            0.0                       0.0
20                            NaN                       NaN
21                            0.0                       0.0
22                            0.0                       0.0
23                            0.0                       0.0
24                            0.0                       0.0
25                            0.0                       0.0
26                            0.0                       0.0
27                            0.0                       0.0
28                            0.0                       0.0
29                            NaN                       NaN
...                           ...                       ...
307481                        0.0                       0.0
307482                        0.0                       0.0
307483                        0.0                       0.0
307484                        NaN                       NaN
307485                        0.0                       0.0
307486                        0.0                       0.0
307487                        0.0                       0.0
307488                        0.0                       0.0
307489                        0.0                       0.0
307490                        0.0                       0.0
307491                        0.0                       0.0
307492                        0.0                       0.0
307493                        0.0                       0.0
307494                        0.0                       0.0
307495                        0.0                       0.0
307496                        0.0                       0.0
307497                        0.0                       0.0
307498                        0.0                       0.0
307499                        0.0                       0.0
307500                        0.0                       0.0
307501                        NaN                       NaN
307502                        0.0                       0.0
307503                        0.0                       0.0
307504                        NaN                       NaN
307505                        0.0                       0.0
307506                        NaN                       NaN
307507                        NaN                       NaN
307508                        1.0                       0.0
307509                        0.0                       0.0
307510                        0.0                       0.0


檢視資料中各個欄位類型的數量

In [3]:
app_train.dtypes.value_counts()

float64    65
int64      41
object     16
dtype: int64

檢視資料中類別型欄位各自類別的數量

In [4]:
app_train.select_dtypes(include=["object"]).apply(pd.Series.nunique, axis = 0)

NAME_CONTRACT_TYPE             2
CODE_GENDER                    3
FLAG_OWN_CAR                   2
FLAG_OWN_REALTY                2
NAME_TYPE_SUITE                7
NAME_INCOME_TYPE               8
NAME_EDUCATION_TYPE            5
NAME_FAMILY_STATUS             6
NAME_HOUSING_TYPE              6
OCCUPATION_TYPE               18
WEEKDAY_APPR_PROCESS_START     7
ORGANIZATION_TYPE             58
FONDKAPREMONT_MODE             4
HOUSETYPE_MODE                 3
WALLSMATERIAL_MODE             7
EMERGENCYSTATE_MODE            2
dtype: int64

#### Label encoding
有仔細閱讀[參考資料](https://medium.com/@contactsunny/label-encoder-vs-one-hot-encoder-in-machine-learning-3fc273365621)的人可以發現，Label encoding 的表示方式會讓同一個欄位底下的類別之間有大小關係 (0<1<2<...)，所以在這裡我們只對有類別數量小於等於 2 的類別型欄位示範使用 Label encoding，但不表示這樣處理是最好的，一切取決於欄位本身的意義適合哪一種表示方法

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
# Create a label encoder object
le = LabelEncoder()
le_count = 0

# Iterate through the columns
for col in app_train:
    if app_train[col].dtype == 'object':
        # If 2 or fewer unique categories
        if len(list(app_train[col].unique())) <= 2:
            # Train on the training data
            le.fit(app_train[col])
            # Transform both training and testing data
            app_train[col] = le.transform(app_train[col])
            app_test[col] = le.transform(app_test[col])
            
            # Keep track of how many columns were label encoded
            le_count += 1
            
print('%d columns were label encoded.' % le_count)

3 columns were label encoded.

#### One Hot encoding
pandas 中的 one hot encoding 非常方便，一行程式碼就搞定

In [7]:
app_train = pd.get_dummies(app_train)
app_test = pd.get_dummies(app_test)

print(app_train['CODE_GENDER_F'].head())
print(app_train['CODE_GENDER_M'].head())
print(app_train['NAME_EDUCATION_TYPE_Academic degree'].head())

0    0
1    1
2    0
3    1
4    0
Name: CODE_GENDER_F, dtype: uint8
0    1
1    0
2    1
3    0
4    1
Name: CODE_GENDER_M, dtype: uint8
0    0
1    0
2    0
3    0
4    0
Name: NAME_EDUCATION_TYPE_Academic degree, dtype: uint8

可以觀察到原來的類別型欄位都轉為 0/1 了

## 作業
將下列部分資料片段 sub_train 使用 One Hot encoding, 並觀察轉換前後的欄位數量 (使用 shape) 與欄位名稱 (使用 head) 變化

In [8]:
app_train = pd.read_csv(f_app_train)
sub_train = pd.DataFrame(app_train['WEEKDAY_APPR_PROCESS_START'])
print(sub_train.shape)
sub_train.head()

(307511, 1)

  WEEKDAY_APPR_PROCESS_START
0                  WEDNESDAY
1                     MONDAY
2                     MONDAY
3                  WEDNESDAY
4                   THURSDAY

In [ ]:
"""
Your Code Here
"""